[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "build"  # Remove 'frontend/' prefix
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200